version: '3'
services:
  springboot-app:
    container_name: springapp
    image: hacker123shiva/springboot-app
    restart: always
    # build: .
    ports:
      - '9000:9000'
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: blog_app_apis
      MYSQL_ROOT_PASSWORD: root
